sgi_homepage:
    path:     /
    defaults: { _controller: SGIBundle:Bl:index }

grid:
    path:     /grid
    defaults: { _controller: SGIBundle:Default:grid }

griddos:
    path:     /griddos
    defaults: { _controller: SGIBundle:Default:griddos }

calendar:
    path:     /calendar
    defaults: { _controller: SGIBundle:Default:calendar }
